rotki/rotki.com

- components/Header.vue
- components/Hero.vue
- components/download/DownloadButton.vue
- components/features/Features.vue
- components/features/details/Dashboard.vue
- components/features/details/Defi.vue
- components/features/details/DefiDetails.vue
- components/features/details/Exchanges.vue
- components/features/details/ProfitLossReport.vue
- components/features/menu/MiddleMenu.vue
- components/hero/UseApp.vue
- components/plans/Plans.vue
- components/plans/details/AdvancedPlan.vue
- components/plans/details/BasicPlan.vue
- components/plans/details/CustomPlan.vue
- components/plans/details/FreePlan.vue
- components/premium/Premium.vue
- components/premium/details/DexSupport.vue
- components/premium/details/GetPremium.vue
- components/premium/details/GraphsStatistics.vue
- components/premium/details/PremiumDefi.vue
- components/premium/details/PremiumStaking.vue
- components/premium/details/Transactions.vue
- locales/en.json
- nuxt.config.js
- package.json
- tsconfig.json
- yarn.lock
Fix #15 
- Fix Typos
DeFi protocol or on one of the supported exchanges.
Should be: Be it on a blockchain,
a DeFi protocol or on one of the supported exchanges.
> Fix dashboard wording

- components/Hero.vue
- components/Links.vue
- components/checkout/pay/CardPayment.vue
- components/checkout/pay/PaypalPayment.vue
- components/checkout/plan/PlanSelection.vue
- components/plans/blocks/Plan.vue
- components/premium/details/GetPremium.vue
- nuxt.config.js
- pages/checkout/pay/card.vue
- pages/checkout/pay/paypal.vue
- server-middleware/csp.ts
- store/index.ts
- utils/csp-guard.ts
> Introduces custom csp for card payment page

- components/download/DownloadDialog.vue
To not forget to include it in the next deployment.
> Fixes the fallback github releases link

- components/jobs/BackendDeveloper.vue
- components/jobs/FrontendDeveloper.vue
- components/jobs/JobsContent.vue
- components/jobs/UiUxDesigner.vue
- pages/jobs/ui-ux.vue
@LefterisJP check also the other ads to see if any changes are required there.
> Adds job ad for ui/ux designer

- components/account/login/LoginForm.vue
> Fixes /login 500 error

- components/account/CountrySelect.vue
- components/account/InputField.vue
- components/account/password/PasswordForm.vue
- components/account/signup/SignupForm.vue
- components/common/ExternalLink.vue
- components/common/Recaptcha.client.vue
- composables/repatcha.ts
- nuxt.config.ts
- types/recaptcha.d.ts
> Replace recaptcha module

- .github/workflows/ci.yml
I noticed this was not part of the pipelines this morning, I skipped it during commit.
> add test runner to pipeline after linting

- .gitignore
- cypress.config.ts
- package.json
- pages/index.vue
- pnpm-lock.yaml
- tests/e2e/fixtures/example.json
- tests/e2e/specs/pages/index.spec.cy.ts
- tests/e2e/support/commands.ts
- tests/e2e/support/e2e.ts
> enable download dialog on main page

- components/account/home/AccountOverview.vue
- components/account/home/SubscriptionTable.vue
- components/checkout/common/PaymentFrame.vue
- components/checkout/payment-method/PaymentMethodPage.vue
- components/checkout/payment-method/PaymentMethodSelection.vue
- components/checkout/plan/ChangePlanDialog.vue
- components/checkout/plan/PlanSelection.vue
- package.json
- pnpm-lock.yaml
- tests/mocks/handlers.ts
- tests/setup.ts
Adds two new [rules](https://github.com/rotki/eslint-config/releases/tag/v1.0.4)
> chore: update eslint-config

- layouts/jobs.vue
- package.json
- pages/jobs/backend.vue
- pages/jobs/frontend.vue
- pages/jobs/index.vue
- pnpm-lock.yaml
> Re arrange jobs pages files

- plugins/redirect.ts
> add permanent page redirect for renamed product details route

- Dockerfile
Closes #79
https://wener.me/notes/devops/container/buildkit#run-mount
> feat: adds docker `--mount=type=cache`

- components/download/DownloadDocs.vue
- components/download/DownloadHeading.vue
- components/download/DownloadItem.vue
- components/download/DownloadPreview.vue
- locales/en.json
- tests/e2e/specs/pages/index.spec.cy.ts
> style: adjust download page in mobile screen

- components/account/password/PasswordForm.vue
- components/account/signup/SignupAddress.vue
- components/account/signup/SignupForm.vue
- components/footer/FooterIconLinks.vue
- composables/repatcha.ts
- content/jobs/1.backend.md
- content/jobs/2.frontend.md
> Updates discord links to point to landing page

- components/jobs/JobDetail.vue
- composables/markdown.ts
- pages/jobs/[id].vue
> fix: not found jobs to return 404 instead 500

- components/account/home/AccountAddress.vue
- components/account/home/AccountInformation.vue
- locales/en.json
- nuxt.config.ts
> fix: moved offline bug

- locales/en.json
> fix: typos

- content/jobs/3.ui-ux.md
Fixed typo in the job description.
> Fixed typo in 3.ui-ux.md

- .github/pull_request_template.md
- components/account/home/PremiumPlaceholder.vue
- components/footer/PageFooter.vue
- components/header/PageHeader.vue
- utils/external-links.ts
> feat: implement seasonal logo

- server/middleware/csp.ts
> fix: add rotki/data to csp img-src

- .nuxtignore
- Dockerfile
- package.json
- pnpm-lock.yaml
- tsconfig.build.json
> chore: set cypress as optional dependencies

- components/error/NotFoundError.vue
resolves https://github.com/rotki/rotki.com/pull/194#pullrequestreview-1946761274
> fix: center content on 404 page for mobile screens

- components/checkout/pay/CardForm.vue
- components/checkout/pay/HostedField.vue
- components/jobs/JobTag.vue
> feat: placeholder for card expirationDate field

- components/checkout/pay/CardPayment.vue
- store/payments/cards.ts
> fix: disallow original nonce being send to verify

- components/checkout/pay/CardPayment.vue
- store/payments/cards.ts
- types/index.ts
Closes #(issue_number)
It does not seem to have any actual effect other than logging the error but in any case it's better to not have it
> fix: change parsing model to avoid parsing error being logged

- components/checkout/pay/PaypalPayment.vue
- store/payments/paypal.ts
- types/index.ts
> fix: update paypal checkout flow to properly vault the card

- components/account/home/PremiumPlaceholder.vue
- components/common/AppLogo.vue
- components/footer/PageFooter.vue
- components/header/PageHeader.vue
- utils/external-links.ts
> fix: render app logo on client side with fallback to default for ssr

- locales/en.json
> chore: adjust texts for payment flow

- components/account/home/SubscriptionTable.vue
- locales/en.json
> feat: add payment link on subscription table when status is pending

- components/account/home/SubscriptionTable.vue
- components/checkout/pay/CryptoPage.vue
- components/checkout/pay/CryptoRequest.vue
- components/checkout/payment-method/PaymentMethodSelection.vue
- types/payment.ts
> fix: resolves a bug with crypto renewal

- components/checkout/pay/CryptoPage.vue
> fix: resolves renewal error when changing plan after nav

- package.json
- pnpm-lock.yaml
> chore: bump rollup and remove overwrite

- components/checkout/pay/CryptoAssetSelector.vue
- components/checkout/pay/CryptoChainIcon.vue
- components/checkout/pay/CryptoPaymentForm.vue
- locales/en.json
- utils/text.ts
> feat: hide token contract address

- components/account/home/PremiumPlaceholder.vue
- components/common/AppLogo.vue
- components/footer/PageFooter.vue
- package.json
- pnpm-lock.yaml
- server/middleware/csp.ts
- utils/external-links.ts
part of https://github.com/orgs/rotki/projects/11/views/2?pane=issue&itemId=58082972
> Feat: apply logo changes

- Dockerfile
- components/account/home/SubscriptionTable.vue
- locales/en.json
- types/index.ts
> feat: subscription status 'cancelled but still active'

- package.json
> chore: release v1.17.0

- components/checkout/payment-method/PaymentMethodSelection.vue
- components/footer/FooterIconLinks.vue
- components/home/DynamicMessageDisplay.vue
- components/home/HomeBanner.vue
- components/home/PremiumFeatures.vue
- components/jobs/JobTag.vue
- components/values/ValueContact.vue
- components/values/ValueVision.vue
- composables/dynamic-message.ts
- composables/random-stepper.ts
- package.json
- pages/index.vue
- pnpm-lock.yaml
- types/dynamic-messages.ts
> feat: add dynamic message

- components/common/NavigationMenu.vue
- components/download/DownloadDocs.vue
- components/footer/FooterNavigation.vue
> refactor: update docs link

- nuxt.config.ts
> chore: update dev proxy origin to avoid csrf braking

- package.json
> chore: release v1.22.0

- public/integrations/all.json
> feat: update integration data

- components/account/home/PaymentsTable.vue
- components/account/home/SubscriptionTable.vue
> style: align table actions to right

- package.json
- pnpm-lock.yaml
> chore: update ui-library to v1.5.0

- components/checkout/pay/CryptoPaymentForm.vue
- composables/crypto-payment.ts
- layouts/account.vue
> Bugfixes for crypto payments

- public/integrations/all.json
> feat: update integration list

- components/account/home/PaymentsTable.vue
- i18n/locales/en.json
- types/index.ts
> fix: add support for refunded payments on ui

- package.json
- pnpm-lock.yaml
> chore: remove resolutions for vite

- package.json
- pnpm-lock.yaml
> fix: update the ui-library to fix the left icon in the landing page

- components/checkout/payment-method/CheckMark.vue
- nuxt.config.ts
> fix: update wrong checkmark icon

- components/home/testimonials/TestimonialCarousel.vue
- content.config.ts
- nuxt.config.ts
> Updates robots.txt and fixes v-bind for Testimonials

- .github/workflows/ci.yml
- Dockerfile
- package.json
- pages/jobs/[id].vue
> Fix mising conditional that would show role unavailable to open roles

- server/middleware/csp.ts
> fix: add script-src-elem to CSP to avoid firefox errors

- server/middleware/csp.ts
> fix: adds recaptcha urls to script-src-elem & connect

- server/middleware/csp.ts
> fix: update content security policy for chrome

- components/home/features/details/EvmProtocols.vue
- components/integration/IntegrationDetails.vue
- composables/integrations.ts
- public/integrations/all.json
> feat: update protocols data

- package.json
> chore: release v1.32.0

- i18n/locales/en.json
- pages/bespoke.vue
> chore: add calendly button to bespoke accounting

- components/checkout/plan/PlanSelection.vue
- composables/plan.ts
- i18n/locales/en.json
- middleware/valid-plan-id.ts
- pages/checkout/pay/card.vue
- pages/checkout/pay/crypto.vue
- pages/checkout/pay/method.vue
- pages/checkout/pay/paypal.vue
- pages/checkout/pay/request-crypto.vue
- store/index.ts
- store/tiers.ts
- types/index.ts
- utils/countries.ts
> feat(frontend): tier pricing based on the country

- composables/crypto-payment.ts
- composables/web3-connection.ts
- layouts/account.vue
> chore: web3 connection refactoring

- components/common/NavigationMenu.vue
- components/header/PageHeader.vue
fix this because of the NFT work
> style: adjust the navbar

- composables/web3-connection.ts
- content.config.ts
- content/sponsorship-tiers/bronze.md
- content/sponsorship-tiers/gold.md
- content/sponsorship-tiers/silver.md
- i18n/locales/en.json
- package.json
- pages/sponsor/sponsor.vue
- pages/sponsor/submit-name.vue
- pnpm-lock.yaml
> fix: update NFT wording

- server/api/ens/avatar.get.ts
- utils/use-logger.ts
> fix: improve ENS avatar error handling

- components/sponsor/NftSubmissionForm.vue
> feat: automatically check NFT when the `tokenId` is updated

- composables/rotki-sponsorship/use-payment-tokens.ts
- pages/sponsor/mint.vue
> fix(frontend): improvement for the prices

- i18n/locales/en.json
- pages/sponsor/submit-name.vue
> feat: add terms note for NFT submission

- composables/rotki-sponsorship/constants.ts
> fix: update mainnet RPC for sponsorship

- composables/rotki-sponsorship/use-payment-tokens.ts
> fix: wrong format number

- composables/dynamic-message.ts
- composables/integrations.ts
- composables/rotki-sponsorship/config.ts
- composables/rotki-sponsorship/constants.ts
- composables/rotki-sponsorship/payment.ts
- composables/rotki-sponsorship/types.ts
- composables/use-fetch-with-csrf.ts
- pages/sponsor/leaderboard.vue
- pages/sponsor/mint.vue
- server/api/nft/image.get.ts
- server/api/nft/tier-info.get.ts
- server/utils/cache-updater.ts
- server/utils/nft-config.ts
- store/index.ts
- store/sponsorship-metadata.ts
- types/sponsor.ts
- utils/object.ts
> fix: update the ipfs gateway

- composables/rotki-sponsorship/config.ts
- composables/rotki-sponsorship/constants.ts
- composables/rotki-sponsorship/contract.ts
- composables/rotki-sponsorship/metadata.ts
- composables/rotki-sponsorship/payment.ts
- composables/rotki-sponsorship/rpc-checker.ts
- i18n/locales/en.json
- pages/sponsor/mint.vue
- server/utils/nft-config.ts
- store/sponsorship-metadata.ts
> fix: remove fallback

- composables/use-fetch-with-csrf.ts
- plugins/startup.ts
- server/plugins/nft-cache-updater.ts
- server/tasks/nft/cache.ts
- server/utils/cache-updater.ts
- server/utils/image-cache.ts
- server/utils/image-core.ts
- server/utils/nft-core.ts
> Fixes session cookie tracking for CSP redirect and reduces logging on nfts

- composables/rotki-sponsorship/rpc-checker.ts
> fix: destroy provider if it's failed and not used

- packages/website/nuxt.config.ts
- packages/website/server/routes/robots.txt.ts
> feat: dynamically generate the robots.txt

- packages/website/nuxt.config.ts
> fix: add crossOriginResourcePolicy for payment-methods page

- packages/website/nuxt.config.ts
> fix: add crossOriginEmbedderPolicy for payment-methods page
